Repository varnishcache/varnish-cache, pull requests merged in 2019-10, with the labels that each got.

#3074 fix regression: ban-lurker skips objects
  bin/varnishd/cache/cache_ban_lurker.c
  bin/varnishtest/tests/c00049.vtc
Labels: r=6.0

#3078 Update docs for supported VCL versions
  doc/sphinx/reference/vcl.rst
Labels: a=OK'ed

#3058 Make waitinglist rushes propagate on streaming delivery
  bin/varnishd/cache/cache_fetch.c
  bin/varnishd/cache/cache_hash.c
  bin/varnishd/cache/cache_req_fsm.c
  bin/varnishtest/tests/c00097.vtc
  bin/varnishtest/tests/c00098.vtc
  bin/varnishtest/tests/c00099.vtc
Labels: r=6.0

#3021 Add a VRT_HashStrands32 utility
  bin/varnishd/cache/cache_vrt.c
  bin/varnishtest/tests/d00003.vtc
  include/vrt.h
  lib/libvmod_directors/hash.c
  lib/libvmod_directors/shard_cfg.c
  lib/libvmod_directors/shard_dir.c
  lib/libvmod_directors/shard_dir.h
  lib/libvmod_directors/vmod_shard.c
Labels: a=OK'ed, b=enhancement, c=varnishd, c=vmod, r=6.0, r=trunk

#3107 yield to newly bred threads
  bin/varnishd/cache/cache_wrk.c
Labels: b=enhancement, c=varnishd, r=6.0, r=trunk
