Repository varnishcache/varnish-cache, pull requests merged in 2019-05, with the labels that each got.

#2992 Ban lurker optimalization: Remove from ban list when possible
  bin/varnishd/cache/cache_ban.c
  bin/varnishd/cache/cache_ban_lurker.c
Labels: a=OK'ed

#2996 Kill strcat and strcpy usage in VIN_n_Arg
  lib/libvarnish/vin.c
Labels: a=OK'ed, b=bug, c=varnishapi, r=6.0, r=trunk

#3000 Add Debug to the default VSL mask
  bin/varnishd/mgt/mgt_param_bits.c
  bin/varnishtest/vtc_varnish.c
Labels: a=OK'ed, b=enhancement, c=varnishd, c=varnishtest, r=6.0, r=trunk
