Repository varnishcache/varnish-cache, pull requests merged in 2020-06, with the labels that each got.

#3350 Backport send_timeout
  bin/varnishd/http1/cache_http1_line.c
  bin/varnishtest/tests/r03189.vtc
Labels: c=varnishd, r=6.0

#3332 varnish.m4: Support generated VCC files
  varnish.m4
Labels: b=enhancement, c=build, c=packaging, c=vmod, r=trunk

#3315 Diffentiate "no backend" from "none resolved" in VDI_Resolve()
  bin/varnishd/cache/cache_director.c
  include/vrt.h
  lib/libvcc/vcc_expr.c
Labels: a=RunByUPLEX
