Repository varnishcache/varnish-cache, pull requests merged in 2021-08, with the labels that each got.

#3656 vcl: Change the order of sess.* variables
  bin/varnishtest/tests/r03564.vtc
  doc/sphinx/reference/vcl_var.rst
Labels: b=bug, c=doc, c=varnishd, r=6.0

#3660 [Backport] Add MAIN.esi_req counter for ESI subrequests
  bin/varnishd/VSC_main.vsc
  bin/varnishd/cache/cache_esi_deliver.c
  bin/varnishtest/tests/e00003.vtc
Labels: r=6.0

#3638 vcl: Allow header names to be quoted (compliance improvements)
  bin/varnishtest/tests/b00076.vtc
  doc/sphinx/reference/vcl_var.rst
  lib/libvcc/vcc_symb.c
  lib/libvcc/vcc_var.c
Labels: b=enhancement, r=trunk, c=varnishd, r=7.0

#3662 [6.0] vcc: Insert the built-in source last
  lib/libvcc/vcc_compile.c
  lib/libvcc/vcc_compile.h
Labels: b=enhancement, c=varnishd, r=6.0

#3566 vsl: New "fetch status" field for Hit records
  bin/varnishd/cache/cache_hash.c
  bin/varnishd/cache/cache_req.c
  bin/varnishd/cache/cache_req_fsm.c
  bin/varnishd/cache/cache_varnishd.h
  bin/varnishtest/tests/b00077.vtc
  include/tbl/vsl_tags.h
Labels: b=enhancement, r=trunk, c=varnishd, c=varnishlog, r=6.0
