Repository varnishcache/varnish-cache, pull requests merged in 2024-09, with the labels that each got.

#4112 Generalize the VDP API: all in vdp_ctx
  bin/varnishd/cache/cache_deliver_proc.c
  bin/varnishd/cache/cache_esi_deliver.c
  bin/varnishd/cache/cache_filter.h
  bin/varnishd/cache/cache_gzip.c
  bin/varnishd/cache/cache_range.c
  bin/varnishd/cache/cache_req_fsm.c
  bin/varnishd/cache/cache_varnishd.h
  bin/varnishd/cache/cache_vrt_filter.c
  bin/varnishd/http2/cache_http2_deliver.c
  vmod/vmod_debug.c
Labels: a=need bugwash, a=ActionBeforeRelease

#4171 vcc_action: Accept strings returned by vmods for return(fail())
  bin/varnishtest/tests/v00018.vtc
  lib/libvcc/vcc_action.c
Labels: a=freeze

#4182 obj: List transient flags in a single place
  bin/varnishd/cache/cache.h
  bin/varnishd/cache/cache_deliver_proc.c
  bin/varnishd/cache/cache_hash.c
  bin/varnishd/cache/cache_obj.c
Labels: b=enhancement, r=trunk, c=varnishd

#4188 tests get larger thread pool, necessary for ppc32
  bin/varnishtest/tests/e00016.vtc
  bin/varnishtest/tests/e00029.vtc
  bin/varnishtest/tests/e00030.vtc
  bin/varnishtest/tests/e00034.vtc
  bin/varnishtest/tests/l00003.vtc
  bin/varnishtest/tests/r01737.vtc
  bin/varnishtest/tests/r01781.vtc
  bin/varnishtest/tests/r01878.vtc
  bin/varnishtest/tests/r02849.vtc
  bin/varnishtest/tests/v00042.vtc
  bin/varnishtest/tests/v00043.vtc
Labels: b=bug, r=trunk, c=varnishd, c=varnishtest

#4190 vcc: Internal type for the reserved 'default' symbol
  bin/varnishtest/tests/c00042.vtc
  lib/libvcc/vcc_backend.c
  lib/libvcc/vcc_compile.h
  lib/libvcc/vcc_expr.c
  lib/libvcc/vcc_symb.c
  lib/libvcc/vcc_types.c
Labels: b=bug, b=enhancement, r=trunk, c=varnishd, b=cleanup
