Repository varnishcache/varnish-cache, pull requests merged in 2025-04, with the labels that each got.

#4310 vrt: Harmonize regexp error messages
  bin/varnishd/cache/cache_vrt_re.c
Labels: b=enhancement, r=trunk, c=varnishd

#4307 gzip: Allocate gzip buffers from storage
  bin/varnishd/cache/cache_esi_fetch.c
  bin/varnishd/cache/cache_gzip.c
  bin/varnishd/cache/cache_vgz.h
  include/tbl/params.h
Labels: b=enhancement, r=trunk, c=varnishd

#4261 Add BANIDX facility to speed up BAN loading
  bin/varnishd/Makefile.am
  bin/varnishd/cache/cache_ban.c
  bin/varnishd/cache/cache_ban.h
  bin/varnishd/cache/cache_ban_idx.c
Labels: a=need bugwash, a=last call

#4306 param: Off by one maximum http_req_overflow_status
  include/tbl/params.h
Labels: b=enhancement, r=trunk, c=varnishd

#4317 vtree: Inject contextual parent checks during import
  tools/import_vtree_from_freebsd.sh
Labels: b=enhancement, r=trunk
